// Generated by GraphWalker (http://www.graphwalker.org)
package main;

import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

@Model(file = "com/mc646/MultiGraph.json")
public interface MultiGraphTestInterface {

    @Vertex()
    void v_ExcecaoIdJaUsado();

    @Edge()
    void e_removeAresta();

    @Edge()
    void e_removeNoInexistente();

    @Edge()
    void e_limpaGrafo();

    @Vertex()
    void v_inicio();

    @Vertex()
    void v_grafoNaoVazio();

    @Edge()
    void e_removeUltimoNo();

    @Edge()
    void e_adicionaNoExistente();

    @Edge()
    void e_adicionaArestaEmNoInexistente();

    @Edge()
    void e_removeNo();

    @Edge()
    void e_criaGrafo();

    @Edge()
    void e_adicionaNo();

    @Edge()
    void e_adicionaAresta();

    @Vertex()
    void v_grafoVazio();

    @Edge()
    void e_adicionaArestaExistente();

    @Vertex()
    void v_ElementoNaoEncontrado();
}
